### ISSUE TITLE
error with strain and cycle number

### ISSUE THREAD

**Issue by pavlo888** [yoavram/curveball#153]
Hi, 

I am very interested in using this tool for analysis but I am getting an error when trying to run the test data from the tutorial. 

I have installed the package in a Conda environment using python3. When I run the following command:

`curveball analyse Tecan_280715.xlsx --plate_file=G-RG-R.csv --ref_strain=G`

I get the following error: 

`/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/seaborn/axisgrid.py:243: UserWarning: The `size` parameter has been renamed to `height`; please update your code.
  warnings.warn(msg, UserWarning)

Traceback (most recent call last):
  File "/Users/pablo/opt/anaconda2/envs/curveball/bin/curveball", line 8, in <module>
    sys.exit(cli())
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/curveball/scripts/cli.py", line 254, in analyse
    file_results = _process_file(filepath, plate, blank_strain, ref_strain, max_time, guess, param_min, param_max, param_fix, weights, ci, nsamples)
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/curveball/scripts/cli.py", line 304, in _process_file
    g = curveball.plots.plot_strains(df, output_filename=strains_plot_fn)
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/curveball/plots.py", line 131, in plot_strains
    grp = data.groupby(by=by)
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/pandas/core/frame.py", line 5801, in groupby
    return groupby_generic.DataFrameGroupBy(
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 402, in __init__
    grouper, exclusions, obj = get_grouper(
  File "/Users/pablo/opt/anaconda2/envs/curveball/lib/python3.8/site-packages/pandas/core/groupby/grouper.py", line 598, in get_grouper
    raise KeyError(gpr)
KeyError: ('Strain', 'Cycle Nr.')`

Could you please help me solve this issue? 

Thanks. 

Pablo

**Comment by yoavram** [comment]
Someone else just notified me about this via email. I’ll try to figure it out soon after the holiday.
